### PR TITLE
added safety checks

### PR DESCRIPTION
**Pull request by alextrical**
Pull request to add the following functionality:
Thermal panic protection when the temperature doesn't change fast enough when outside range.
Thermal panic protection when the temperature suddenly changes by more than x degrees.
Protection added for thermistor defects, such as shorts, missing sensors, or over temperature.

### CODE REVIEW

**Comment by aamott** [comment]
Thanks for the contribution! It looks like the formatting all got changed. Would you mind undoing the formatting changes or running it back through the Arduino IDE? It makes it a little hard to tell what got changed. I ran it through the [simulator](https://wokwi.com/projects/333363618182595154) and it seems to work normally, but I'd like to test the safety checks.

**Comment by aamott** [comment]
I just added an enhancement request detailing a little more room for potential improvement on this. We may solve the thermal runaway problem in a couple of pull requests. 
#3 - Thermal Panic Mode

**Comment by alextrical** [comment]
The formatting in question was done by ArduinIDE's auto formatting option, so I have re applied the changes to a clean copy. Please give it a try and see how it works for you

**Comment by aamott** [comment]
Looks like that fixed the formatting differences. I wonder, are you using Arduino IDE 1.x? I'm on 2. Maybe they format differently. Much easier to see the changes now, and they look good! Have you had the chance to test this on a working system yet?

**Comment by aamott** [comment]
I finally got to test this on my system. When I short the thermistor wires, it continues heating but disables heating in the menu. I'll try to add a menu mode for failures so you can just call a function, input a message, and have it automatically disable the heater and puller.

**Comment by aamott** [comment]
I ended up changing a lot of things, including adding a new menu item to display errors and disable everything when needed. Thank you for the contribution though!

**Pull request closed without merging**
